spring:
  rabbitmq:
    autoStartup: true
    host: 127.0.0.1
    port: 5672
    username: guest
    pasword: guest
    virtual-host: desenvolvimento
    
# para configuracoes simples de retentativa
#    listener:
#      simple:
#        retry:
#          enabled: true
#          initial-interval: 3s
#          max-attempts: 2
#          max-interval: 10s
#          multiplier: 1


